---
- name: Install GenLayer validator using collection role
  hosts: genlayer_nodes
  become: true
  collections:
    - validatrium.genlayer
  roles:
    - role: validator
      vars:
        zksync_http: "https://YOUR-ZKSYNC-HTTP"
        zksync_ws: "wss://YOUR-ZKSYNC-WS"
        genlayer_version: "latest"
        genlayer_password: "CHANGE_ME"
        backup_passphrase: "CHANGE_ME_BACKUP"
